
create database uniDB;
go

use uniDB;
go


CREATE TABLE CLIENTE
( 
	IDCLIENTE            integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCLIENTE PRIMARY KEY (IDCLIENTE ASC)
)
go



CREATE TABLE EMPLEADO
( 
	IDEMPLEADO           integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	USUARIO              varchar(20)  NOT NULL ,
	CLAVE                varchar(20)  NOT NULL ,
	CONSTRAINT XPKEMPLEADO PRIMARY KEY (IDEMPLEADO ASC)
)
go



CREATE TABLE VENTA
( 
	IDVENTA              integer IDENTITY ( 1,1 ) ,
	IDCLIENTE            integer  NOT NULL ,
	IDEMPLEADO           integer  NOT NULL ,
	SUBTOTAL             numeric(10,2)  NOT NULL ,
	IMPUESTO             numeric(10,2)  NOT NULL ,
	TOTAL                numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKVENTA PRIMARY KEY (IDVENTA ASC),
	CONSTRAINT R_2 FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_7 FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE TIPO_PAGO
( 
	IDTIPO               integer  NOT NULL ,
	NOMBRE_CORTO         varchar(20)  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKTIPO_PAGO PRIMARY KEY (IDTIPO ASC)
)
go



CREATE TABLE PAGO
( 
	IDPAGO               integer IDENTITY ( 1,1 ) ,
	IDTIPO               integer  NOT NULL ,
	IDVENTA              integer  NOT NULL ,
	IMPORTE              numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKPAGO PRIMARY KEY (IDPAGO ASC),
	CONSTRAINT R_6 FOREIGN KEY (IDTIPO) REFERENCES TIPO_PAGO(IDTIPO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_5 FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE CATEGORIA
( 
	IDCATEGORIA          integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	CONSTRAINT XPKCATEGORIA PRIMARY KEY (IDCATEGORIA ASC)
)
go



CREATE TABLE PRODUCTO
( 
	IDPRODUCTO           integer IDENTITY ( 1,1 ) ,
	IDCATEGORIA          integer  NOT NULL ,
	NOMBRE               varchar(100)  NOT NULL ,
	PRECIO               numeric(10,2)  NOT NULL ,
	STOCK                integer  NULL ,
	CONSTRAINT XPKPRODUCTO PRIMARY KEY (IDPRODUCTO ASC),
	CONSTRAINT R_1 FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE DETALLE_VENTA
( 
	IDDETALLE            integer IDENTITY ( 1,1 ) ,
	IDVENTA              integer  NOT NULL ,
	IDPRODUCTO           integer  NOT NULL ,
	PRECIO_VENTA         numeric(10,2)  NOT NULL ,
	CANTIDAD             numeric(10,2)  NOT NULL ,
	SUBTOTAL             numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKDETALLE_VENTA PRIMARY KEY (IDDETALLE ASC),
	CONSTRAINT R_4 FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_3 FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go


